# Generated by Django 3.0.8 on 2020-08-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=225, null=True, verbose_name='First Name')),
                ('lastName', models.CharField(blank=True, max_length=225, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email Subscribe')),
                ('accepted', models.BooleanField(default=False, verbose_name='Accept Policy')),
            ],
            options={
                'ordering': (),
            },
        ),
    ]
