# Generated by Django 3.0.7 on 2020-07-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_auto_20200711_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
